/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : GPIO.c
**     Project     : kpb64_test
**     Processor   : SKEAZ64MLH4
**     Component   : GPIO_LDD
**     Version     : Component 01.128, Driver 01.08, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2023-02-07, 11:45, # CodeGen: 55
**     Abstract    :
**         The HAL GPIO component will provide a low level API for unified
**         access to general purpose digital input/output pins across
**         various device designs.
**
**         RTOS drivers using HAL GPIO API will be simpler and more
**         portable to various microprocessors.
**     Settings    :
**          Component name                                 : GPIO
**          Port                                           : GPIOA
**          Port width                                     : 32 bits
**          Mask of allocated pins                         : 0x0
**          Interrupt service/event                        : Disabled
**          Bit fields                                     : 0
**          Initialization                                 : 
**            Auto initialization                          : no
**            Event mask                                   : 
**              OnPortEvent                                : Disabled
**     Contents    :
**         Init                   - LDD_TDeviceData* GPIO_Init(LDD_TUserData *UserDataPtr);
**         Deinit                 - void GPIO_Deinit(LDD_TDeviceData *DeviceDataPtr);
**         SetPortValue           - void GPIO_SetPortValue(LDD_TDeviceData *DeviceDataPtr, GPIO_TPortValue Value);
**         GetPortValue           - GPIO_TPortValue GPIO_GetPortValue(LDD_TDeviceData *DeviceDataPtr);
**         ClearPortBits          - void GPIO_ClearPortBits(LDD_TDeviceData *DeviceDataPtr, GPIO_TPortValue Mask);
**         SetPortBits            - void GPIO_SetPortBits(LDD_TDeviceData *DeviceDataPtr, GPIO_TPortValue Mask);
**         TogglePortBits         - void GPIO_TogglePortBits(LDD_TDeviceData *DeviceDataPtr, GPIO_TPortValue Mask);
**         SetPortInputDirection  - void GPIO_SetPortInputDirection(LDD_TDeviceData *DeviceDataPtr,...
**         SetPortOutputDirection - void GPIO_SetPortOutputDirection(LDD_TDeviceData *DeviceDataPtr,...
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file GPIO.c
** @version 01.08
** @brief
**         The HAL GPIO component will provide a low level API for unified
**         access to general purpose digital input/output pins across
**         various device designs.
**
**         RTOS drivers using HAL GPIO API will be simpler and more
**         portable to various microprocessors.
*/         
/*!
**  @addtogroup GPIO_module GPIO module documentation
**  @{
*/         

/* MODULE GPIO. */

#include "GPIO.h"
/* {Default RTOS Adapter} No RTOS includes */
#include "IO_Map.h"
#include "PE_Fix_Types.h"

#ifdef __cplusplus
extern "C" {
#endif 

typedef struct {
  LDD_TUserData *UserData;             /* RTOS device data structure */
} GPIO_TDeviceData, *GPIO_TDeviceDataPtr; /* Device data structure type */
/* {Default RTOS Adapter} Static object used for simulation of dynamic driver memory allocation */
static GPIO_TDeviceData DeviceDataPrv__DEFAULT_RTOS_ALLOC;
const static GPIO_MemMapPtr cGpioModuleBaseAddr[GPIO_MAX_TYPE] = {GPIOA_BASE_PTR, GPIOB_BASE_PTR, GPIOC_BASE_PTR};
/*
** ===================================================================
**     Method      :  GPIO_Init (component GPIO_LDD)
*/
/*!
**     @brief
**         This method initializes the associated peripheral(s) and the
**         component internal variables. The method is called
**         automatically as a part of the application initialization
**         code.
**     @param
**         UserDataPtr     - Pointer to the RTOS device
**                           structure. This pointer will be passed to
**                           all events as parameter.
**     @return
**                         - Pointer to the dynamically allocated private
**                           structure or NULL if there was an error.
*/
/* ===================================================================*/
LDD_TDeviceData* GPIO_Init(LDD_TUserData *UserDataPtr)
{
  /* Allocate LDD device structure */
  GPIO_TDeviceData *DeviceDataPrv;
  /* {Default RTOS Adapter} Driver memory allocation: Dynamic allocation is simulated by a pointer to the static object */
  DeviceDataPrv = &DeviceDataPrv__DEFAULT_RTOS_ALLOC;
  /* Save RTOS Device structure */
  DeviceDataPrv->UserData = UserDataPtr; /* Store the RTOS device structure */
  /* Registration of the device structure */
  PE_LDD_RegisterDeviceStructure(PE_LDD_COMPONENT_GPIO_ID,DeviceDataPrv);
  return ((LDD_TDeviceData *)DeviceDataPrv);
}

/*
** ===================================================================
**     Method      :  GPIO_Deinit (component GPIO_LDD)
*/
/*!
**     @brief
**         This method disables the device and frees the device data
**         structure memory.
**     @param
**         DeviceDataPtr   - Pointer to device data
**                           structure pointer.
*/
/* ===================================================================*/
void GPIO_Deinit(LDD_TDeviceData *DeviceDataPtr)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  /* Unregistration of the device structure */
  PE_LDD_UnregisterDeviceStructure(PE_LDD_COMPONENT_GPIO_ID);
  /* Deallocation of the device structure */
  /* {Default RTOS Adapter} Driver memory deallocation: Dynamic allocation is simulated, no deallocation code is generated */
}

/*
** ===================================================================
**     Method      :  GPIO_SetPortValue (component GPIO_LDD)
*/
/*!
**     @brief
**         This method writes the output data value to the port. Only
**         configured pins (through all of bit fields in this component)
**         are affected.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Value           - Unaligned data value to write to the
**                           port. The bit 0 corresponds with the pin
**                           which has index 0 within the port, the bit
**                           1 corresponds with the pin which has index
**                           1 within the port, etc. Only configured
**                           pins (through all of bit fields in this
**                           component) are affected.
*/
/* ===================================================================*/
void GPIO_SetPortValue(LDD_TDeviceData *DeviceDataPtr, GPIO_BASE_Type GpioType, GPIO_TPortValue Value)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  if(GpioType > GPIO_MAX_TYPE)
  {
    return;
  }
  GPIO_PDD_SetPortDataOutput(cGpioModuleBaseAddr[GpioType],
    (GPIO_PDD_GetPortDataOutput(cGpioModuleBaseAddr[GpioType])
      & ((GPIO_TPortValue)(~((GPIO_TPortValue)GPIO_ALLOCATED_PINS_MASK))))
    | (((GPIO_TPortValue)(Value)) & ((GPIO_TPortValue)GPIO_ALLOCATED_PINS_MASK)));
}

/*
** ===================================================================
**     Method      :  GPIO_GetPortValue (component GPIO_LDD)
*/
/*!
**     @brief
**         This method returns the current port input data value. Only
**         configured pins (through all of bit fields in this component)
**         are returned.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Unaligned current port input data value
**                           masked for allocated pins of the port. The
**                           bit 0 corresponds with the pin which has
**                           index 0 within the port, the bit 1
**                           corresponds with the pin which has index 1
**                           within the port, etc. Only configured pins
**                           (through all of bit fields in this
**                           component) are returned. The others are
**                           zeros.
*/
/* ===================================================================*/
GPIO_TPortValue GPIO_GetPortInputValue(LDD_TDeviceData *DeviceDataPtr, GPIO_BASE_Type GpioType)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  if(GpioType > GPIO_MAX_TYPE)
  {
    return NULL;
  }
  return (GPIO_TPortValue)(GPIO_PDD_GetPortDataInput(cGpioModuleBaseAddr[GpioType])
    & ((GPIO_TPortValue)GPIO_ALLOCATED_PINS_MASK));
}

/*
** ===================================================================
**     Method      :  GPIO_GetPortOutputValue (component GPIO_LDD)
*/
/*!
**     @brief
**         This method returns the current port input data value. Only
**         configured pins (through all of bit fields in this component)
**         are returned.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Unaligned current port input data value
**                           masked for allocated pins of the port. The
**                           bit 0 corresponds with the pin which has
**                           index 0 within the port, the bit 1
**                           corresponds with the pin which has index 1
**                           within the port, etc. Only configured pins
**                           (through all of bit fields in this
**                           component) are returned. The others are
**                           zeros.
*/
/* ===================================================================*/
GPIO_TPortValue GPIO_GetPortOutputValue(LDD_TDeviceData *DeviceDataPtr, GPIO_BASE_Type GpioType)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  if(GpioType > GPIO_MAX_TYPE)
  {
    return NULL;
  }
  return (GPIO_TPortValue)(GPIO_PDD_GetPortDataOutput(cGpioModuleBaseAddr[GpioType])
    & ((GPIO_TPortValue)GPIO_ALLOCATED_PINS_MASK));
}
/*
** ===================================================================
**     Method      :  GPIO_ClearPortBits (component GPIO_LDD)
*/
/*!
**     @brief
**         This method drives the specified bits of the port to the
**         inactive level. Only configured pins (through all of bit
**         fields in this component) are affected.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Mask            - Unaligned mask of bits to setting the
**                           inactive level. Each port pin has
**                           corresponding bit in the mask. Bit value 0
**                           means not selected bit, bit value 1 means
**                           selected bit. The bit 0 corresponds with
**                           the pin which has index 0 within the port,
**                           the bit 1 corresponds with the pin which
**                           has index 1 within the port, etc. Only
**                           configured pins (through all of bit fields
**                           in this component) are affected.
*/
/* ===================================================================*/
void GPIO_ClearPortBits(LDD_TDeviceData *DeviceDataPtr, GPIO_BASE_Type GpioType, GPIO_TPortValue Mask)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  if(GpioType > GPIO_MAX_TYPE)
  {
    return;
  }
  GPIO_PDD_ClearPortDataOutputMask(cGpioModuleBaseAddr[GpioType],
    ((GPIO_TPortValue)(((GPIO_TPortValue)GPIO_ALLOCATED_PINS_MASK) & ((GPIO_TPortValue)(Mask)))));
}

/*
** ===================================================================
**     Method      :  GPIO_SetPortBits (component GPIO_LDD)
*/
/*!
**     @brief
**         This method drives the specified bits of the port to the
**         active level. Only configured pins (through all of bit
**         fields in this component) are affected.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Mask            - Unaligned mask of bits to setting the
**                           active level. Each port pin has
**                           corresponding bit in the mask. Bit value 0
**                           means not selected bit, bit value 1 means
**                           selected bit. The bit 0 corresponds with
**                           the pin which has index 0 within the port,
**                           the bit 1 corresponds with the pin which
**                           has index 1 within the port, etc. Only
**                           configured pins (through all of bit fields
**                           in this component) are affected.
*/
/* ===================================================================*/
void GPIO_SetPortBits(LDD_TDeviceData *DeviceDataPtr, GPIO_BASE_Type GpioType, GPIO_TPortValue Mask)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  if(GpioType > GPIO_MAX_TYPE)
  {
    return;
  }
  GPIO_PDD_SetPortDataOutputMask(cGpioModuleBaseAddr[GpioType],
    ((GPIO_TPortValue)(((GPIO_TPortValue)GPIO_ALLOCATED_PINS_MASK) & ((GPIO_TPortValue)(Mask)))));
}

/*
** ===================================================================
**     Method      :  GPIO_TogglePortBits (component GPIO_LDD)
*/
/*!
**     @brief
**         This method inverts the specified bits of the port to
**         another level. Only configured pins (through all of bit
**         fields in this component) are affected.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Mask            - Unaligned mask of bits to inverting the
**                           current level. Each port pin has
**                           corresponding bit in the mask. Bit value 0
**                           means not selected bit, bit value 1 means
**                           selected bit. The bit 0 corresponds with
**                           the pin which has index 0 within the port,
**                           the bit 1 corresponds with the pin which
**                           has index 1 within the port, etc. Only
**                           configured pins (through all of bit fields
**                           in this component) are affected.
*/
/* ===================================================================*/
void GPIO_TogglePortBits(LDD_TDeviceData *DeviceDataPtr, GPIO_BASE_Type GpioType, GPIO_TPortValue Mask)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  if(GpioType > GPIO_MAX_TYPE)
  {
    return;
  }
  GPIO_PDD_TogglePortDataOutputMask(cGpioModuleBaseAddr[GpioType],
    ((GPIO_TPortValue)(((GPIO_TPortValue)GPIO_ALLOCATED_PINS_MASK) & ((GPIO_TPortValue)(Mask)))));
}

/*
** ===================================================================
**     Method      :  GPIO_SetPortInputDirection (component GPIO_LDD)
*/
/*!
**     @brief
**         This method sets the specified pins of the port to the input
**         direction. Only configured pins (through all of bit fields
**         in this component) are affected.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Mask            - Mask of bits to setting the input
**                           direction. Each port pin has corresponding
**                           bit in the mask. Bit value 0 means not
**                           selected bit, bit value 1 means selected
**                           bit. The bit 0 corresponds with the pin
**                           which has index 0 within the port, the bit
**                           1 corresponds with the pin which has index
**                           1 within the port, etc. Only configured
**                           pins (through all of bit fields in this
**                           component) are affected.
*/
/* ===================================================================*/
void GPIO_SetPortInputDirection(LDD_TDeviceData *DeviceDataPtr, GPIO_BASE_Type GpioType, GPIO_TPortValue Mask)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  if(GpioType > GPIO_MAX_TYPE)
  {
    return;
  }
  GPIO_PDD_SetPortInputDirectionMask(cGpioModuleBaseAddr[GpioType],
    ((GPIO_TPortValue)GPIO_ALLOCATED_PINS_MASK) & ((GPIO_TPortValue)(Mask)));
}

/*
** ===================================================================
**     Method      :  GPIO_SetPortOutputDirection (component GPIO_LDD)
*/
/*!
**     @brief
**         This method sets the specified pins of the port to the
**         output direction. The specified pins of the port will be
**         driven to specified states. Only configured pins (through
**         all of bit fields in this component) are affected.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Mask            - Mask of bits to setting the output
**                           direction. Each port pin has corresponding
**                           bit in the mask. Bit value 0 means not
**                           selected bit, bit value 1 means selected
**                           bit. The bit 0 corresponds with the pin
**                           which has index 0 within the port, the bit
**                           1 corresponds with the pin which has index
**                           1 within the port, etc. Only configured
**                           pins (through all of bit fields in this
**                           component) are affected.
**     @param
**         Value           - Unaligned port data value to appear on
**                           the specified port pins after they have
**                           been switched to the output direction.
*/
/* ===================================================================*/
void GPIO_SetPortOutputDirection(LDD_TDeviceData *DeviceDataPtr, GPIO_BASE_Type GpioType, GPIO_TPortValue Mask, GPIO_TPortValue Value)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  if(GpioType > GPIO_MAX_TYPE)
  {
    return;
  }
  GPIO_PDD_SetPortDataOutput(cGpioModuleBaseAddr[GpioType],
    ((GPIO_TPortValue)(GPIO_PDD_GetPortDataOutput(cGpioModuleBaseAddr[GpioType])
      & ((GPIO_TPortValue)(~((GPIO_TPortValue)(((GPIO_TPortValue)GPIO_ALLOCATED_PINS_MASK)
        & ((GPIO_TPortValue)(Mask))))))))
    | (((GPIO_TPortValue)(Value))
      & ((GPIO_TPortValue)(((GPIO_TPortValue)GPIO_ALLOCATED_PINS_MASK) & ((GPIO_TPortValue)(Mask))))));
  GPIO_PDD_SetPortOutputDirectionMask(cGpioModuleBaseAddr[GpioType],
    ((GPIO_TPortValue)GPIO_ALLOCATED_PINS_MASK) & ((GPIO_TPortValue)(Mask)));
}

/* END GPIO. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
